import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import utilStyles from "../styles/utils.module.scss";
import { Layout } from "../components";

import { getSortedPostsData } from "../lib/posts";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

interface IHomeProps {
  allPostsData: any;
}

const Home: NextPage<IHomeProps> = ({
  allPostsData,
}: IHomeProps): JSX.Element => {
  console.log("%c 🧀 allPostsData", "color:#3f7cff", allPostsData);
  return (
    <Layout home>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <ul>
          <li>
            <Link href={"/"}>Home</Link>
          </li>
          <li>
            <Link href={"./Feed"}>Feed</Link>
          </li>
        </ul>
      </nav>

      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <main>Home content</main>

      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
        <ul className={utilStyles.list}>
          {/* {allPostsData.map(({ id, date, title }) => (
            <li className={utilStyles.listItem} key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))} */}
        </ul>
      </section>
    </Layout>
  );
};

export default Home;
